### ISSUE TITLE
.NET Standard 1.1?

### ISSUE THREAD

**Issue by dprothero** [viniciusmelquiades/jwt#1]
How realistic would it be for this library to target .NET Standard 1.1? Working on a library trying to target 1.1 but need the JWT package. Doesn't work at the moment due to this package targeting .NET Standard 1.3.

**Comment by viniciusmelquiades** [comment]
Sorry for the delay. I really don't remember why I use netstandard 1.3. I think one of the libs has a dependency on JSON.NET and it uses netstandard 1.3, at least at the time. But I can't remember why the core library is 1.3. 

I'll have a look at it tomorrow and get back to you ASAP.

**Comment by viniciusmelquiades** [comment]
@dprothero Sorry for the delay to answer again.

I tested the code targeting .NET Standard 1.0, but it failed to compile because version 1.0 doesn't have the System.Security.Cryptography libs, and it is required.

The solution would be to fork it and have it use a lib outside .NET to do that, if possible. That`s something I don't want to do for now.

However, the team at the original project have opened an [issue](https://github.com/jwt-dotnet/jwt/issues/55) to discuss the migration plan to version 2.0 (I just found out about it, and plan to offer help). It looks like the new architecture will make it easier to replace the missing libs in .NET Standard 1.0 (if replacements exists, that is).

If you really need this ported to .NET Standard 1.0 ASAP, you could fork my version and fix I yourself. I would accept the merge request and publish it to Nuget so your team can use it.

Either way, I'm closing this issue.
